name: Conda Builds

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  build-and-deploy:
    name: Build and Deploy
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8']
        architecture: ['x86', 'x64']
        exclude:
          # Don't build 32-bit on Mac or Linux
          - os: macos-latest
            architecture: x86

          - os: ubuntu-latest
            architecture: x86

    runs-on: ${{ matrix.os }}

    steps:
      # This LOOKS like it is checking out 'master', but it is using the 'master' version of the checkout action
      # It is actually checking out the most recent version on this branch
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Conda
        uses: s-weigand/setup-conda@v1.0.3
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Fix conda path on Windows
        if: matrix.os == 'windows-latest'
        run: set PATH=%PATH%;C:\Miniconda\Library\bin
        shell: cmd

      - name: Install Conda requirements
        run: conda install anaconda conda-build

      - name: Build and test Conda distribution
        run: conda build recipe